feat: 이미지 처리 구현
keepsaker/back-memory pull request #14
Opened 2023-08-10 14:14 UTC by HubCreator

### 🛠️ Issue

- close #12 

### ✅ Tasks
- 추억 새기기 기능에서 이미지 처리 및 영속화
- 추억 새기기 기능에서 좌표 추출 및 영속화
- ImageController 구현
- GlobalExceptionHandler 작성

### ⏰ Time
- 2 -> 5

### 📝 Note
-

2023-08-13 06:20 UTC, youngh0 approved these changes
헙크 너무 고생 많으셨습니다.

이미지 처리 코드를 보니 대단하시네요.. ImageHandler에 대한 단위 테스트가 없긴한데 어떤걸 테스트할지 고민해보니 애매한 감이 있네요. (파일명도 현재 시간이 붙고 그래서..)

그래서 저는 어푸르브 하겠습니다!! 너무 고생많았으요 😄

2023-08-13 06:20 UTC, youngh0 commented on our-memory/src/main/java/keepsake/ourmemory/OurMemoryApplication.java
>  @SpringBootApplication
import에 EnableJpaAuditing은 추가됐는데 어노테이션은 없는데 혹시 확인 가능할까요??

2023-08-13 06:20 UTC, youngh0 commented on our-memory/src/main/java/keepsake/ourmemory/domain/image/ImageHandler.java
> +        if (!directory.exists()) {
지금 저희 로컬에 저장하기 때문에 이렇게 directory존재 유무를 파악하는 걸까요?

2023-08-13 06:20 UTC, youngh0 commented on our-memory/src/main/java/keepsake/ourmemory/application/repository/MemoryRepository.java
> +    @EntityGraph(attributePaths = {"images"})
오.. 엔티티 그래프..

2023-08-13 06:20 UTC, youngh0 commented on our-memory/src/main/java/keepsake/ourmemory/domain/image/ImageHandler.java
> +    public List<Image> upload(List<MultipartFile> multipartFiles) throws IOException {
함수명이 upload인데 실질적으로 수행하는 일은 MultipartFile을 Image객체로 변경하는 일 같아요. 그래서 뭐 convert이런 네이밍도 괜찮지 않을까 싶습니다!

2023-08-13 06:20 UTC, youngh0 commented on our-memory/src/main/java/keepsake/ourmemory/domain/image/ImageHandler.java
> +        System.out.println(imageRootPath);
열심히 디버깅한 흔적이네요.. 영광의 상처.. 환경변수로 설정한 directory값이 잘 바인딩 됐는지 확인하기 위한걸까요?

2023-08-13 06:20 UTC, youngh0 commented on our-memory/src/main/java/keepsake/ourmemory/domain/image/ImageHandler.java
> +        return now.format(DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss"));
현재 시간으로 포매팅하는거 너무 좋네요 ㅎ

2023-08-13 06:57 UTC, HubCreator commented on our-memory/src/main/java/keepsake/ourmemory/domain/image/ImageHandler.java
> +        if (!directory.exists()) {
아뇨 그냥 방어 로직입니다! 혹시나 해당 경로에 디렉터리가 존재하지 않는다면 새로 만들어서 넣어라!

2023-08-13 06:59 UTC, HubCreator commented on our-memory/src/main/java/keepsake/ourmemory/application/repository/MemoryRepository.java
> +    @EntityGraph(attributePaths = {"images"})
특정 추억에 대한 내용을 가져올 때에는 이미지도 항상 들고와야 하기 때문에, 해당 쿼리에 페치 조인을 걸어줬습니다!

2023-08-13 07:01 UTC, HubCreator commented on our-memory/src/main/java/keepsake/ourmemory/domain/image/ImageHandler.java
> +    public List<Image> upload(List<MultipartFile> multipartFiles) throws IOException {
실제 파일을 추출해 저장하는 로직도 있어서, `saveAndConvert`로 수정했습니다!

2023-08-13 07:02 UTC, HubCreator commented on our-memory/src/main/java/keepsake/ourmemory/domain/image/ImageHandler.java
> +        System.out.println(imageRootPath);
ㅋㅋㅋㅋ네 제거했습니다!

2023-08-13 07:03 UTC, HubCreator commented on our-memory/src/main/java/keepsake/ourmemory/OurMemoryApplication.java
>  @SpringBootApplication
아 맞아요! 요거 h2 콘솔에서 직접 값 넣다가 BaseEntity가 기본적으로 값을 만들어주지 않아서 요렇게 테스트 했던 것 같아요. 롤백하겠습니다!

2023-08-14 14:02 UTC, jundonghyuk approved these changes
고생하셨습니다 .. 

멀티파트파일 다루시느라..

2023-08-14 14:02 UTC, jundonghyuk commented on our-memory/src/main/java/keepsake/ourmemory/application/memory/MemoryService.java
> +
혹시 extractor의 역할을 하는 객체로 따로 빼는건 어떻게 생각하세요 ?

2023-08-14 14:02 UTC, jundonghyuk commented on our-memory/src/main/java/keepsake/ourmemory/application/repository/MemoryRepository.java
> +    @EntityGraph(attributePaths = {"images"})
ㅠㅅ ㅠ 공부해야겠군요  엔티티그래프..

2023-08-14 14:07 UTC, jundonghyuk requested changes

2023-08-14 14:07 UTC, jundonghyuk commented on our-memory/src/main/java/keepsake/ourmemory/application/memory/MemoryService.java
> +        }
먼가 메소드로 따로 빼도될것같은느뀜 ?

2023-08-14 14:07 UTC, jundonghyuk commented on our-memory/src/main/resources/application.yml
> +      on-profile: prod
하나의 yml파일에서 구분하시는군요 !
저는 아예 파일을 따로 작성해서, 한파일에 모는것도 나쁘지 않아보이네요.

중요한건 환경변수처리하구요

2023-08-14 14:07 UTC, jundonghyuk approved these changes

2023-08-14 14:33 UTC, HubCreator commented on our-memory/src/main/java/keepsake/ourmemory/application/memory/MemoryService.java
> +
유틸성이라서 staic 메서드를 가지는 CoordinateExtractor로 분리해봤어요! 좋은데요?!

2023-08-14 14:36 UTC, HubCreator commented on our-memory/src/main/java/keepsake/ourmemory/application/memory/MemoryService.java
> +        }
인자의 갯수가 많아지긴 하지만, Memory를 객체화 하는데 애초에 많은 인자가 필요해서 괜찮을 것 같아요! 분리했습니다~!

2023-08-14 15:52 UTC, merged