Feature/3 find category
keepsaker/back-memory pull request #4
Opened 2023-07-31 13:37 UTC by jundonghyuk

### 🛠️ Issue

- close #3

### ✅ Tasks
- 카테고리 목록을 조회한다

### ⏰ Time
- 2023.7.31:21:00-> 2021.7.31:22:00

### 📝 Note
- enum을 순회하고 응답하기 때문에 따로 데이터베이스에 붙지는 않습니다. 그렇기에 일단 서비스 레이어에 트랜잭션을 걸지 않았어요.
- 서비스 레이어가 레포지토리를 의존하고 있지 않기에 서비스 단위테스트는 생략했습니다.

2023-07-31 16:30 UTC, youngh0 requested changes
깔쌈하네요 하디씨

대댓글만 달아주시면 어프루브 바로 하겠슴다~

2023-07-31 16:30 UTC, youngh0 commented on our-memory/src/main/java/keepsake/ourmemory/api/memory/response/CategoriesResponse.java
> +    public CategoriesResponse() {
Protected로 막는거 어떠신가여

2023-07-31 16:30 UTC, youngh0 commented on our-memory/src/main/java/keepsake/ourmemory/api/memory/response/CategoryResponse.java
> +    public static CategoryResponse from(CategoryDto categoryDto) {
String name만 받아도 될 것 같은데 정팩메 사용하신 이유가 궁금합니다~

2023-07-31 16:30 UTC, youngh0 commented on our-memory/src/test/java/keepsake/ourmemory/acceptance/memory/MemoryAcceptanceTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
추후 데이터 초기화 어떻게 할지 정해지면 수정해야되는 부분이겠죠??

2023-07-31 23:28 UTC, HubCreator approved these changes
빠르게 구현하셨군여! 고생하셨슴다!!

2023-07-31 23:28 UTC, HubCreator commented on our-memory/src/main/java/keepsake/ourmemory/api/memory/MemoryController.java
> +                        .toList());
서비스에서 컨트롤러로 dto로 넘겨준 다음에, 컨트롤러에서 응답값을 재구성하는 방식이군여!

이것도 컨벤션으로 한 번 얘기해보는 시간이 있으면 좋을 것 같네요 ㅎㅎㅎ

2023-07-31 23:28 UTC, HubCreator commented on our-memory/src/test/java/keepsake/ourmemory/acceptance/memory/MemoryAcceptanceTest.java
> +    void 카테고리_목록을_조회한다() {
요렇게만 해도 displayname에 뜨나요?!?

2023-07-31 23:28 UTC, HubCreator commented on our-memory/src/test/java/keepsake/ourmemory/acceptance/memory/MemoryAcceptanceTest.java
> +        assertThat(names).containsExactlyInAnyOrderElementsOf(expected);
멋지네요 쏘쿨

2023-08-01 13:40 UTC, jundonghyuk commented on our-memory/src/main/java/keepsake/ourmemory/api/memory/response/CategoryResponse.java
> +    public static CategoryResponse from(CategoryDto categoryDto) {
method reference를 쓰고 싶은 제욕심이었던것 같습니다. 가독성이 많이 떨어질까요 ?

2023-08-01 13:40 UTC, jundonghyuk commented on our-memory/src/test/java/keepsake/ourmemory/acceptance/memory/MemoryAcceptanceTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
어어어 어떤 뜻일까요 ?

2023-08-01 13:41 UTC, jundonghyuk commented on our-memory/src/test/java/keepsake/ourmemory/acceptance/memory/MemoryAcceptanceTest.java
> +    void 카테고리_목록을_조회한다() {
확인해보겠습니다 !! ㅠㅠㅋ

2023-08-07 08:43 UTC, youngh0 commented on our-memory/src/main/java/keepsake/ourmemory/api/memory/response/CategoryResponse.java
> +    public static CategoryResponse from(CategoryDto categoryDto) {
음 그냥 name필드 하나만 받아서 new로 생성해도 인자가 하나라 굳이 정팩메로 한 이유가 있는지 궁금했어요!

2023-08-07 08:43 UTC, youngh0 commented on our-memory/src/test/java/keepsake/ourmemory/acceptance/memory/MemoryAcceptanceTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
랜덤 포트라 데이터 삭제해야되는데 어떻게 할지 정해지면 해당 부분도 변경되어야 하는지 물어본겁니다!

2023-08-07 08:44 UTC, youngh0 approved these changes

2023-08-07 12:14 UTC, merged