Feature/2
keepsaker/back-memory pull request #5
Opened 2023-07-31 14:59 UTC by youngh0

### 🛠️ Issue

- close #2 

### ✅ Tasks
- 추억 생성 api작성

### ⏰ Time
- 21:00 -> 23:30

### 📝 Note
- 컨트롤러 테스트는 일단 webMvcTest썼습니다. 아직 테스트 격리 템플릿 안짜서 restAssured는 패스했습니다.
- Title, Content의 길이 검사를 객체에서 또 해야할까요? dto에서 validation만 하면 충분할지 확신이 안서네요.. 여러분의 의견이 궁금합니당

2023-08-01 10:11 UTC, HubCreator approved these changes
코드 잘 봤습니다. 고생하셨어요 !!

2023-08-01 10:11 UTC, HubCreator commented on our-memory/src/main/java/keepsake/ourmemory/domain/memory/Category.java
> +    private static final Map<String, Category> categories =
캐싱 멋있는데요?!

2023-08-01 10:11 UTC, HubCreator commented on our-memory/src/main/java/keepsake/ourmemory/domain/memory/Category.java
> +    }
Lombok의 @Getter를 사용할 수 있을 것 같아요!

2023-08-01 10:11 UTC, HubCreator commented on our-memory/src/main/java/keepsake/ourmemory/application/memory/MemoryService.java
> +@Transactional
Service 전체 레벨에서는 `readOnly = true`를 설정해주고, 조회를 제외한 나머지 메서드단에서만 `@Transactional`을 붙여주는 것은 어떨까요?!
현재엔 전체 레벨에 쓰기용 트랜잭션이 걸려있어서 조회 메서드에도 쓰기용이 걸릴 것 같아요

2023-08-01 10:11 UTC, HubCreator commented on our-memory/src/main/java/keepsake/ourmemory/application/memory/MemoryService.java
> +        return memory.getId();
아마 pk 생성 전략이 IDENTITY여서, save를 호출함과 동시에 쿼리문이 날라가고 memory의 id값이 채워져서 영속성 컨테이너에 관리될 것 같습니다. 따라서 현재처럼 memory의 id를 바로 리턴해도 문제가 없을 것 같아요.

하지만 생성 전략에 조금 덜 영향을 받도록 `memoryRepository.save(memory)`의 리턴값인 `Memory savedMemory`의 id를 반환하도록 하는 것은 어떨까요?! 그저.. 노파심에 의견 말해봅니다 ㅎㅎㅎ

2023-08-01 10:11 UTC, HubCreator commented on our-memory/src/main/java/keepsake/ourmemory/domain/memory/Memory.java
> +        this(memberId, title, category, visitedAt, star, content, null);
Coordinate 값이 없는 상황에서 외부에서 null을 주입하기보다, `Coordinate.empty()` 같은 객체를 넣어주는 것은 어떨까요?

2023-08-01 10:11 UTC, HubCreator commented on our-memory/src/main/java/keepsake/ourmemory/domain/memory/Title.java
> +        }
검증 멋있네요! 문자열이 empty인 경우 혹은 null인 경우도 체크해주면 좋을 것 같아요!

그리고 이에 따라 db 컬럼 제약 `@Clolumn(length=50)`도 추가하면 좋을 것 같아요 ㅎㅎㅎ

2023-08-01 10:11 UTC, HubCreator commented on our-memory/src/test/java/keepsake/ourmemory/api/MemoryControllerTest.java
> +
테스트 꼼꼼하시네여... 쏘 쿠우울

2023-08-01 13:18 UTC, jundonghyuk requested changes
고생하셨어요 레오 코드 잘봤습니다 ㅇ_ㅇ!

커멘트 각각에 남겼어용

2023-08-01 13:18 UTC, jundonghyuk commented on our-memory/src/main/java/keepsake/ourmemory/application/memory/MemoryService.java
> +        return memory.getId();
궁금한게 있는데, 생성전략이 다르면 `memory`와 `savedMemory`의 동일성이 보장되지 않나요 ?

영속성 컨텍스트내에서는 어쨌든 동일성이 보장되어 `memoryRepository.save(memory)에 의해 `memory`자체가 영속성 컨텍스트 내에서 관리가되고 동일성만 보장된다면 `memory.getId()`를 호출하였을 때 어떤식으로든 `id`값을 생성하여 반환을 해줄 것 같은데 아닌가요 ? (진짜궁금함)

2023-08-01 13:18 UTC, jundonghyuk commented on our-memory/src/main/java/keepsake/ourmemory/domain/memory/Category.java
> +
오호.. 이넘의 `categoryName`값으로 이넘을 조회해도록 한것인가요 ?

good

2023-08-01 13:18 UTC, jundonghyuk commented on our-memory/src/test/java/keepsake/ourmemory/domain/memory/CategoryTest.java
> +    }
Category.CAFE의 `categoryName`의 문자열이 바뀌면 실패할 테스트인것 같아요.

```
// given
Category actual = Category.CAFE;
String categoryName = actual.getCategoryName;

// when
Category expected = Category.from(categoryName);

// then 
assertThat(actual).isSameAs(expected);
```
이런식으로 `categoryName`인 `cafe`에 의존하지 않는 방식은 어떠신가요?

2023-08-01 13:18 UTC, jundonghyuk commented on our-memory/src/test/java/keepsake/ourmemory/domain/memory/StarTest.java
> +        assertThat(three).isEqualTo(Star.THREE);
이것도 위와 같은 커멘트입니다 !

2023-08-01 15:20 UTC, HubCreator commented on our-memory/src/main/java/keepsake/ourmemory/application/memory/MemoryService.java
> +@Transactional
이거는 조금 조삼모사인 경향이 있네요! 철회합니다.. 전체 레벨에 쓰기용을 걸어주고 조회 메서드에만 읽기 트랜잭션 애너테이션을 붙여주는게 좋다는 생각으로 바뀌었어요 ㅎㅎㅎ

2023-08-01 15:46 UTC, HubCreator commented on our-memory/src/main/java/keepsake/ourmemory/application/memory/MemoryService.java
> +        return memory.getId();
> 영속성 컨텍스트내에서는 어쨌든 동일성이 보장되어 memoryRepository.save(memory)에 의해 memory자체가 영속성 컨텍스트 내에서 관리가되고 동일성만 보장된다면 memory.getId()를 호출하였을 때 어떤식으로든 id값을 생성하여 반환을 해줄 것 같은데 아닌가요 ? (진짜궁금함)

한 트랜잭션 안에서 하나의 엔티티에 대해서는 무조건 동일성을 보장한다는 말은 맞는 것으로 알고 있어요! 근데 동일성 비교라 주소값을 비교하면 무조건 같다 라는 것 같아요.

여기서 제가 우려했던 것은 memory는 우리가 id 없이 직접 생성한 것이어서, JPA가 어떻게 처리해서 id를 넣어주는지 확인해보지 않고 얘기한 것이었는데.. 이것저것 테스트해보니 어떤 id 생성 전략이더라도 바로바로 id값을 넣어 주더라고여. 

적어도 IDENTITY 전략이면 save 메서드 호출시 쿼리가 바로 날라가서, JPA가 id값을 넣어주겠거니 했었고, 다른 전략들은 save 호출시가 아니라 마지막에 flush 호출시 쿼리가 날라가서 id값을 찍었을 때 NPE가 터질 수 있겠구나 했었는데 아니네요 ㅎㅎ.. 무조건 id값은 제대로 가져오긴 합니다.

지금 그대로 코드 가져가도 좋을 것 같아여 👍

2023-08-07 08:44 UTC, youngh0 commented on our-memory/src/main/java/keepsake/ourmemory/application/memory/MemoryService.java
> +@Transactional
선택의 영역인듯하네요 ㅎ

2023-08-07 08:46 UTC, youngh0 commented on our-memory/src/main/java/keepsake/ourmemory/application/memory/MemoryService.java
> +        return memory.getId();
아 id는 무조건 제대로 가져오나요? 처음 안 사실이네요

2023-08-07 08:46 UTC, youngh0 commented on our-memory/src/main/java/keepsake/ourmemory/domain/memory/Memory.java
> +        this(memberId, title, category, visitedAt, star, content, null);
너무 좋네요

2023-08-07 12:17 UTC, jundonghyuk approved these changes

2023-08-07 12:25 UTC, merged