[BE] 모든 추억 조회 기능 구현
keepsaker/back-memory pull request #6
Opened 2023-08-01 10:14 UTC by HubCreator

### 🛠️ Issue

- close #1 

### ✅ Tasks
-  전체 조회 API 기능 구현

### ⏰ Time
- 1시간 30분 -> 1시간 30분

### 📝 Note
글을 추가하는 기능이 없어서 제대로 테스트를 못했습니다.. 컨벤션이나 스타일에 대해 피드백 받고 싶고,
앞에 기능들 머지되면 충돌 수정하면서 테스트 더 추가하겠습니다.

2023-08-01 13:31 UTC, jundonghyuk requested changes
헙크 코드 잘봤습니다 ! 고생하셨어요 

커멘트 각각 남겼습니다 !

2023-08-01 13:31 UTC, jundonghyuk commented on our-memory/src/main/java/keepsake/ourmemory/application/MemoryService.java
> +@RequiredArgsConstructor
혹시 `@Transactional(readOnly=true) 에 걸려있는 곳에서 `CUD`작업이 일어나면 런타임에 예외를 던지는건가요 ?
컴파일 타임에는 못잡겠죠..?

런타임에 예외를 잡는다면 두 가지 방식이 있을 것 같아요.
1. 클래스단에 `readOnly = true`를 걸어두고 `CUD`작업이 일어나는 메서드에는 `readOnly=false`를 건다.
2. 반대

1.은 만약, `CUD`작업이 일어나는 곳에 까먹고 `@Transactional`을 걸지 않았다면 자동적으로 `@Transactional(readOnly=true)` 가 먹을 것 같습니다. 그렇다면 런타임에 예외가 날 것 같아요. 물론 테스트에서는 다 잡겠지만..ㅋㅋ

2와 같은 경우는 위에서 말했던 상황은 일어나지 않을 것 같고, 조회용 메서드인데 까먹고 `readOnly=true`를 안썼다면, 실행은 되겠지만 성능적인 이슈에서 `readOnly=true`가 없어 약간 나빠질 수 있겠네요 ?

2번 같은 케이스는 잘 돌아가긴 하니 까먹고 `readOnly=true`를 안쓴걸 찾기 어려울 수도 있구요 ?

헙크는 어떤 방식을 더 선호하는지 의견을 듣고싶어용

2023-08-01 13:31 UTC, jundonghyuk commented on our-memory/src/main/java/keepsake/ourmemory/ui/MemoryController.java
> +        return ResponseEntity.ok(responses);
ㅋㅋㅋㅋㅋㅋㅋㅋ 하드코딩 정말 좋아요 ! 회원가입과 로그인을 빨리 구현하고싶어지는군요..

2023-08-01 13:31 UTC, jundonghyuk commented on our-memory/src/main/java/keepsake/ourmemory/application/MemoryService.java
> +                ))
`MemoryResponse`는 `from(Memory memory)` 와 같은 정팩메를 이용해서 자신을 반환하는 거에 대해선 어떻게 생각하시나요?

즉 Response DTO가 Domain(Entity)를 의존하는 것이죠 !

2023-08-01 13:31 UTC, jundonghyuk commented on our-memory/src/main/java/keepsake/ourmemory/application/repository/MemoryRepository.java
> +    List<Memory> findAllByMemberId(Long memberId); // 1 + 1 + 1 번 쿼리가 나갈 것 (쿼리수가 100개 이하 이내에서)
혹시 주석은 어떤 의미일까요 ?

2023-08-01 13:35 UTC, jundonghyuk commented on our-memory/src/main/java/keepsake/ourmemory/application/MemoryService.java
> +                        memory.getMemoryTags()
여기서 lazy였던 memoryTagList를 조회하면서 쿼리가 1번씩 따로따로 나갈까요 ?

2023-08-01 13:36 UTC, jundonghyuk commented on our-memory/src/main/java/keepsake/ourmemory/application/MemoryService.java
> +                                .toList(),
memoryRag -> Tag를 조회할 때 Tag또한 lazy여서 쿼리가 한 번씩 더 나가요 ?

2023-08-01 15:54 UTC, HubCreator commented on our-memory/src/main/java/keepsake/ourmemory/application/MemoryService.java
> +@RequiredArgsConstructor
저는 원래 1번을 선호했습니다! 왜냐하면 조금 더 약한 조건을 class 레벨에 걸어 놓으면, 혹여나 조회 이외의 작업들에 트랜잭션을 붙이지 않았을 때 실패를 하여 무엇이 잘못되었는지 바로바로 알아차릴 수 있기 때문이었습니다.

반대로 class level에 `readOnly = false`로 두었다면 조회 작업에서 애너테이션을 붙이는 것을 까먹더라도 잘 돌아가기 때문에, 뭐가 문제인지도 모르고 지나갈 우려가 있다고 생각해서 1번을 지향했습니다.

그런데 최근에는 뭐.. 2번도 괜찮지 않을까 생각하고 있어요. 기본적으로 모든 메서드들은 트랜잭션으로 묶어주어야 하는데, 사람이 코드를 볼 때 클래스 레벨에 `@Transactional`을 보고 아~ 이 클래스는 트랜잭션이 걸리는구나~ 로 시작하고, 메서드 단에서 조회 로직들만 `@Transactional(readOnly = true)`를 걸어도 이해하기 쉽다.. 라는 의견을 들어서 그럴 수 있겠다~ 생각했습니다.

저는 뭐 이건 진짜 취향차이가 아닐까 생각하고 있어여 ㅎㅎㅎ

2023-08-01 16:00 UTC, HubCreator commented on our-memory/src/main/java/keepsake/ourmemory/application/MemoryService.java
> +                ))
너무 좋은데요..?!

2023-08-01 16:06 UTC, HubCreator commented on our-memory/src/main/java/keepsake/ourmemory/application/MemoryService.java
> +                                .toList(),
윗 코멘트와 함께 설명하자면, 일단 맞습니다! 쿼리가 지금 `Memory` 한 번 불러와서 stream을 돌면서 `MemoryTag`와 `Tag`를 불러오느라 1 + N + M이 터집니다.

하지만 `application.yml`에 정의해 놓은 `jpa.properties.hibernate.default_batch_fetch_size = 100` 설정 때문에 한 번에 가져올 쿼리의 갯수가 100개 이내라면 in절로 한 방에 가져온다! 라고 생각했습니다. 윗쪽의 주석도 그것을 나타낸 것이구요.
그렇다면 결국 1 + N + M 이 개선되어 1 + 1 + 1로 나가지 않을까 예상했습니다.

2023-08-07 03:56 UTC, youngh0 approved these changes
딱히 코멘트 달게 없네요..

하디 리뷰처럼 MemoryResponse생성하는 부분만 정팩메로 깔끔하게 하면 좋을 것 같아요!

2023-08-07 03:56 UTC, youngh0 commented on our-memory/src/main/java/keepsake/ourmemory/domain/memory/Category.java
> +                    .collect(Collectors.toMap(Category::getCategoryName, Function.identity())));
캐싱 너무 좋네요

2023-08-07 03:56 UTC, youngh0 commented on our-memory/src/main/java/keepsake/ourmemory/domain/memory/Memory.java
> +    @OneToMany(fetch = FetchType.LAZY)
혹시 cascade, orphanremoval제거한 이유가 있을까요??

2023-08-07 03:56 UTC, youngh0 commented on our-memory/src/main/java/keepsake/ourmemory/ui/dto/LocationResponse.java
> +public record LocationResponse(String latitude, String longitude) {
오 record좀 치시나요?

2023-08-07 03:56 UTC, youngh0 commented on our-memory/src/main/java/keepsake/ourmemory/application/MemoryService.java
> +@RequiredArgsConstructor
해당 어노테이션 빼먹는 실수를 줄이는 방법으로 명령 조회를 분리하는 방법도 있을 것 같아요!

2023-08-07 03:56 UTC, youngh0 commented on our-memory/src/main/java/keepsake/ourmemory/application/MemoryService.java
> +        List<Memory> memories = memoryRepository.findAll();
이건 임시로 해놓은거죠??

2023-08-07 03:56 UTC, youngh0 commented on our-memory/src/main/java/keepsake/ourmemory/application/MemoryService.java
> +                                .toList(),
컬렉션 조회 최적화 공부를 해야겠군요

2023-08-07 04:00 UTC, HubCreator commented on our-memory/src/main/java/keepsake/ourmemory/domain/memory/Category.java
> +                    .collect(Collectors.toMap(Category::getCategoryName, Function.identity())));
이거 레오 코드임 ㅋㅋㅋㅋ

2023-08-07 04:02 UTC, HubCreator commented on our-memory/src/main/java/keepsake/ourmemory/domain/memory/Memory.java
> +    @OneToMany(fetch = FetchType.LAZY)
oneToMany 단방향에서 cascade, orphanremoval을 붙이면 어떻게 되나요?! 진짜 궁금해서..

2023-08-07 04:02 UTC, HubCreator commented on our-memory/src/main/java/keepsake/ourmemory/ui/dto/LocationResponse.java
> +public record LocationResponse(String latitude, String longitude) {
고럼여

2023-08-07 13:42 UTC, jundonghyuk approved these changes

2023-08-07 13:45 UTC, merged